# -- Name of your distributed application
distributedApplicationName: myapp

microservice:
  # -- Microservice's name
  name: my-microservice
  # -- Microservice's image
  image: mcr.microsoft.com/dotnet/samples:aspnetapp
  # -- Image pull policy
  imagePullPolicy: Always
  # -- Microservice's application HTTP(s) port (80, 443)
  appPort: 8080

# -- Environment variables
env:
  # -- Secret variables binding ENVIRONMENT_VARIABLE = Key in Kubernetes Secret
  secretsBinding:

# -- Deployment configuration
deployment:
  # -- Number of deployment replicas
  replicas: 1

dapr:
  enabled: false
  # id: mymicroservice
  config: dapr-config
  maxRequestSize: "100" # Http max request size (in Mb)

# -- Secrets configuration
secrets:
  # -- Enable secrets
  enable: false

# -- Secret keys variables
secretKeys:
  # -- Kubernetes secret source
  kubernetes-secret: socle-secrets

# -- Health check
healthCheck:
  # -- Probe URL Path
  probePath: "/"

# -- Pod resources variables
resources:
  bestEffort: "false"
  requests:
    # -- Request cpu size (mCores)
    cpu: "50m"
    # -- Request memory size (Mi)
    memory: "256Mi"
  limits:
    # -- Limits cpu size (mCores)
    cpu: "1000m"
    # -- Limits memory size (Mi)
    memory: "2048Mi"
  dapr:
    requests:
      # -- Request dapr sidecar cpu size (mCores)
      cpu: "50m"
      # -- Request dapr memory size (Mi)
      memory: "100Mi"
    limits:
      # -- Limits dapr sidecar cpu size (mCores)
      cpu: "300m"
      # -- Limits dapr sidecar memory size (Mi)
      memory: "1024Mi"

# -- Scaling options
scaling:
  # -- Pod scaling mode (hpa)
  mode: "hpa"
  # -- target CPU for horizontal pod autoscaling
  targetCPUScale: "1300"
  # -- target memory for horizontal pod autoscaling
  targetMemoryScale: "1000"
  # -- minimum replicas in horizontal pod autoscaling
  minReplicas: "1"
  # -- maximum replicas in horizontal pod autoscaling
  maxReplicas: "5"
